version: "2.1"
services:
  admin:
    image: admin
    container_name: admin
    ports:
      - "80:8080"
    depends_on:
      - "mongodb"
  mongodb:
    image: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
networks:
  default:
    external:
      name: mynet
